Integrate storybook visual testing (#67)
* Test commit

* Convert inline styles to classes

* Picasso book adjustments

* Refactor reporter

* Refactor jest environment

* Update snapshots

diff --git a/bin/test-visual b/bin/test-visual
--- a/bin/test-visual
+++ b/bin/test-visual
@@ -11,6 +11,7 @@ BIN_PATH="$BASE_PATH/node_modules/.bin"
 JEST_ENV="$BASE_PATH/puppeteer/environment.js"
 JEST_CONFIG="$BASE_PATH/puppeteer/puppeteer.jest.config.js"
 JEST_TEST_ENV="visual"
+DIFF_OUTPUT_PATH="$BASE_PATH/__diff_output__/*"
 
 function build_storybook() {
   echo -e "${BLUE} Building storybook ... ${NC}"
@@ -27,10 +28,13 @@ function run_jest() {
   fi
 
   set -x
-  $BIN_PATH/jest --testEnvironment=$JEST_ENV --config=$JEST_CONFIG $1
+  $BIN_PATH/jest --testEnvironment=$JEST_ENV --config=$JEST_CONFIG $1 || exit 1
   set +x
 }
 
 yarn install
 build_storybook
+
+# Cleanup old snapshots on every run
+rm -rf $DIFF_OUTPUT_PATH
 run_jest $1
